eureka:
  client:
    service-url:
      defaultZone: http://120.26.171.31:9000/eureka/

logging:
  level:
    com.cloud.agent: debug
    org.springframework.cloud.netflix.feign: debug

spring:
  redis:
    open: true  # 是否开启redis缓存  true开启   false关闭
    database: 0
    host: 120.26.171.31
    port: 6379
    password: wndsb@0825   # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    expireSeconds: 120
    commandTimeout: 10000  #redis操作的超时时间
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.26.171.31:3307/seckill?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: wndsb@0825
seata:
  enabled: true
  application-id: ${spring.application.name}
  service:
    vgroup-mapping:
      product-service-group: seata-server
  config:
    file:
      name: file.conf
  registry:
    type: eureka
    eureka:
      application: seata-server
      service-url: http://120.26.171.31:9000/eureka/
      weight: 1
  enable-auto-data-source-proxy: true
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**Mapper.xml