spring:
  application:
    name: order-service
  profiles:
    active: prod
  cloud:
    alibaba:
      seata:
        tx-service-group: order-service-group
    inetutils:
      timeout-seconds: 10

server:
  port: 9008

###多线程配置
threadPool:
  ###核心线程数
  corePoolSize: 10
  ###最大线程数
  maxPoolSize: 20
  ##  队列容量
  queueCapacity: 16
ribbon:
  ReadTimeout: 10000
#  SocketTimeout: 30000
#  ConnectTimeout: 600
#  MaxAutoRetries: 0
#  MaxAutoRetriesNextServer: 1
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
      fallback:
        enabled: true