spring:
  redis:
    open: true  # 是否开启redis缓存  true开启   false关闭
    database: 0
    host: 120.26.171.31
    port: 6379
    password: wndsb@0825   # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    expireSeconds: 120
    commandTimeout: 10000  #redis操作的超时时间

eureka:
  client:
    service-url:
      defaultZone: http://120.26.171.31:9000/eureka/