spring:
  application:
    name: gateway-service
  profiles:
    active: dev1
  cloud:
    inetutils:
      timeout-seconds: 30
server:
  port: 9002

zuul:
  semaphore:
    max-semaphores: 5000
  #全部服务忽略的敏感头，也可以指定某一个具体的routes
  sensitive-headers: Cookie, Set-Cookie, Authorization, h, t, auth  #看需求取舍要忽略的请求头

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-components: always

# 打印网关日志信息
logging:
  level:
    org.springframework.cloud.gateway: debug

ribbon:
  OkToRetryOnAllOperations: true    #全部请求开启重试机制
  ReadTimeout: 6000                 #请求处理超时时间
  ConnectTimeout: 6000              #请求连接超时时间
  MaxTotalHttpConnections: 1000     #最大http连接数
  MaxConnectionsPerHost: 100        #每个host最大连接数
  MaxAutoRetries: 10                #最大重试次数
  MaxAutoRetriesNextServer: 10      #切换实例的重试次数

hystrix:
  threadpool:
    default:
      coreSize: 1000                      # 线程池数量
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000  # 发生熔断的超时时间
          strategy: SEMAPHORE             # 隔离策略
          semaphore:
            max-semaphores: 2000          # 信号量大小