server:
  port: 8888

spring:
  redis:
    open: true  # 是否开启redis缓存  true开启   false关闭
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456   # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    expireSeconds: 120
    commandTimeout: 10000  #redis操作的超时时间
