#jedis:
#  pool:
#    host: 127.0.0.1
#    port: 6379
#    password: 123456
#    database: 16
#    timeout: 6000ms  # ??????????
#    expireSeconds: 120
#    commandTimeout: 10000  #redis???????
#    config:
#      maxTotal: 1000
#      maxIdle: 10
#      maxWaitMillis: 100000
#
#spring:
#  redis:
#    open: true  # ????redis??  true??   false??
#    database: 0
#    host: 127.0.0.1
#    port: 6379
#    password: 123456       # ????????
#    timeout: 6000ms  # ??????????
#    expireSeconds: 120
#    commandTimeout: 10000  #redis???????
#    jedis:
#      pool:
#        max-active: 5000  # ????????????????????
#        max-wait: -1ms    # ???????????????????????
#        max-idle: 30      # ???????????
#        min-idle: 5       # ???????????


# nohup ./seata-server.sh -h 106.13.234.26 -p 8091 &